### ISSUE TITLE
Display Tangular output in the html page

### ISSUE THREAD

**Issue by hyousef** [petersirka/Tangular#1]
Hi Peter,

I added this line to your fiddle, hoping to see the output, but nothing seen, how to make it:

document.querySelector('#output').html(template2(model));

in the HTML part I added: 
< d i v id='output'>< / d i v>

thanks

**Comment by petersirka** [comment]
Hi @hyousef,
try to add:

```javascript
document.querySelector('body').innerHTML = template2(model);
```

Thanks :+1:

**Comment by hyousef** [comment]
did not work :(

**Comment by petersirka** [comment]
![Screenshot](https://www.online-clipboard.com/142519832746178a0ddcc29cc2b3x28/clipboard.png)

**Comment by hyousef** [comment]
sorry, It worked, It lookd the "d" in document was not copied .

thanks
