### ISSUE TITLE
Quotes problem

### ISSUE THREAD

**Issue by lcnvdl** [petersirka/Tangular#13]
Hello! I'm trying to pass quotes to the template, but it is not showing them as I like.

I'm getting &quot; instead of a normal quote (")

I've tried to use the raw pipe, but it didn't solve my problem

**Comment by petersirka** [comment]
Hi, can you show me your Tangular template?

**Comment by lcnvdl** [comment]
Hi! Thanks for your answer. Yes ,this is the template:

const { start } = require("emvicify");
const settingsFile = require("./settings.json");
const expressSettings = {{ expressSettings }};

start(__dirname, settings.port, { settingsFile, expressSettings }).then(() => {
    console.log(`Listening on port ${settings.port}`);
}, err => {
    console.error("Application failed", err);
});


The value that I'm passing as a parameter is "expressSettings". I'm
trying to write a value like: { "settingA": "A" }

**Comment by petersirka** [comment]
Hi, I have tested it and everything works correctly.

The code below encodes quotes:

```html
 {{ expressSettings }};
```

And this code below renders everything as it is (__try it__):

```html
 {{ expressSettings | raw }};
```
