### ISSUE TITLE
Any plans to add layouts and/or partials?

### ISSUE THREAD

**Issue by rosswaycaster** [petersirka/Tangular#5]
I'm loving how useful this templating engine is and how similar it is to Angular. Is there any plans to add support for layouts and/or partials?

**Comment by petersirka** [comment]
Many thanks :+1: I appreciate it. Currently I don't have any plans to add layouts and partials because this template engine is for templating only. But it's not bad idea :100:

I will think about it.

**Comment by petersirka** [comment]
I rejected the layouts and partials.
Conclusion: it's a simple template engine and it must stay.
